### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by Smolations** [kvendrik/jest-lite#30]
This is a great package but it hasn't been touched in 2 years! The last couple of issues have also not received any responses. Thought I'd check in to find out. Maybe @kvendrik isn't working for Shopify anymore and so no longer has a use for this?  😓

**Comment by kvendrik** [comment]
Hey @Smolations! I currently don't have bandwidth to actively maintain this project but definitely welcome pull requests. Something to keep in mind also is that the core of what makes this work can be [replicated in 7 lines of code](https://github.com/kvendrik/jest-lite/blob/master/src/core.ts).
